global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
 
  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']
 
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
   
